services:

    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_DB: order
        secrets:
            - postgres_password

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

secrets:
    postgres_password:
        file: .dockersecrets/postgres_password.txt
