spring:
  application:
    name: orderlogger
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/orderlogger
    username: postgres
    password: ${postgresPassword}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
postgresPassword: ${POSTGRES_PASSWORD}
---